version: '3.8'
services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile-backend
    command: gunicorn --bind 0.0.0.0:8001 weather_backend.wsgi:application
    volumes:
      - ./BackEnd:/app
      - /app/static
      - /app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - gaucho_weather_network
    restart: always

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile-frontend
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
      - /app/.vite  # Cache de Vite
    ports:
      - "5174:5173"
    depends_on:
      - backend
    networks:
      - gaucho_weather_network
    environment:
      - CHOKIDAR_USEPOLLING=true  # Hot reload en Docker
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - gaucho_weather_network
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - gaucho_weather_network
    restart: always

volumes:
  pg_data:
  redis_data:

networks:
  gaucho_weather_network:
    driver: bridge
